var SpotifyWebApi = require('spotify-web-api-node');
const express = require('express');
const socket = require('socket.io');
const path = require("path");
const app = express();


var credentials = {
    clientId: '59a34986442440bf8b14bdb6c954f17a',
    clientSecret: '970a4174e3514e9ab94bc19e65cc1a2b',
    redirectUri: 'http://192.168.1.12:3000/callback'
  };

var theManWhoSoldTheWorld = {
    "context_uri": "spotify:album:4h9rWFWhgCSSrvIEQ0YhYG",
    "offset": {
      "position": 7
    },
    "position_ms": 0
  }

spotifyApi = new SpotifyWebApi(credentials);

var scopes = ['user-modify-playback-state', 'user-read-email', 'user-read-private', 'user-read-birthdate', 'user-read-playback-state'],
    state;

var loggedIn = false;
var userId;
var playlistUri;
var playlistId;
var playlistSnapshot;

var playlist = [];
var queue_pos = -1;

var last_song;

// wait for callback when someone logs in
app.get('/callback', function (req, res) {
    loggedIn = true;
    var code = req.query.code;

    spotifyApi.authorizationCodeGrant(code).then(
        function(data) {
          console.log('The token expires in ' + data.body['expires_in']);
          console.log('The access token is ' + data.body['access_token']);
          console.log('The refresh token is ' + data.body['refresh_token']);
      
          // Set the access token on the API object to use it in later calls
          spotifyApi.setAccessToken(data.body['access_token']);
          spotifyApi.setRefreshToken(data.body['refresh_token']);
          
          // check who logged in
          spotifyApi.getMe().then(
              function(me) {
                  userId = me.body.display_name;
                  console.log('Authenticated by ' + userId);

                  // set repeat and shuffle to false/off
                  spotifyApi.setRepeat({state: 'off'})
                    .then(function(data) {
                    },function(err) {
                        console.log('Something went wrong in setRepeat()!', err);
                    });
                  spotifyApi.setShuffle({state: 'false'})
                    .then(function(data) {
                    },function(err) {
                        console.log('Something went wrong in setShuffle()!', err);
                    });

                  // check all playlists on account
                  spotifyApi.getUserPlaylists(userId)
                    .then(function(playlists) {

                        // check if 'autogenerated3526' exists
                        var exists = false;
                        playlists.body.items.forEach(function(item) {
                            // if it does...
                            if(item.name == 'autogenerated3526') {
                                console.log('Playlist exists');
                                exists = true;

                                // copy the uri/id
                                playlistUri = item.uri;
                                playlistId = item.id;
                                playlistSnapshot = item.snapshot_id;

                                // remove all tracks in the playlist
                                var positions = [];
                                for(var i = 0; i < item.tracks.total; i++) {
                                    positions.push(i);
                                }
                                spotifyApi.removeTracksFromPlaylistByPosition(item.id, positions, item.snapshot_id)
                                    .then(function(data) {
                                        console.log('Removed all tracks from existing playlist');
                                    }, function(err) {
                                        console.log('Something went wrong in removeTracksFromPlaylistByPosition()!', err);
                                    });
                            }
                        });

                        // if the playlist doesn't exist...
                        if(!exists) {
                            // make it, and copy the uri/id
                            spotifyApi.createPlaylist(userId, 'autogenerated3526', { 'public': true }).then(
                                function(playlist) {
                
                                    console.log('Created New \'autogenerated3526\' Playlist');
                                    playlistUri = playlist.body.uri;
                                    playlistId = playlist.body.id;
                                    playlistSnapshot = playlist.body.snapshot_id;

                                }, function(err) {
                                    console.log('Something went wrong in createPlaylist()!', err);
                                });
                        }
                            
                    },function(err) {
                        console.log('Something went wrong in getUserPlaylists()!', err);
                    });
              }, function(err) {
                  console.log('Something went wrong in getMe()!', err);
              }
          )
          
          // finally, redirect back to normal page
          res.redirect('/');

        },
        function(err) {
          console.log('Something went wrong in authorizationCodeGrant()!', err);
        }
      );

      // set loop to update currently playing track on all clients
      setInterval(
        function () {
            spotifyApi.getMyCurrentPlaybackState().then(
                function(playback) {
                    if(last_song == null) {
                        last_song = playback.body.item.name;
                    } else if(last_song != playback.body.item.name) {
                        if(playback.body.context != null && playlist.length > 0) {
                            queue_pos += 1;
                        }
                    }
        
                    if(playlist.length == 0) {
                        io.sockets.emit('playing', { 'playback': playback, 'playlist': playlist, 'position': queue_pos, 'empty': true, 'client_name': null });
                    } else if(playback.body.context == null) {
                        io.sockets.emit('playing', { 'playback': playback, 'playlist': playlist, 'position': queue_pos, 'empty': false, 'client_name': null });
                    } else {
                        io.sockets.emit('playing', { 'playback': playback, 'playlist': playlist, 'position': queue_pos, 'empty': false, 'client_name': playlist[queue_pos].track.client_name });
                    }
        
                    last_song = playback.body.item.name;
                }, function(err) {
                    console.log('Something went wrong in getMyCurrentPlaybackState()!', err);
                });
            
          }, 2000);
    
  })

app.get('/', function(req, res) {
    if(loggedIn) {
        res.sendFile(path.join(__dirname, 'website/loggedin', 'index.html'));
    } else {
        res.sendFile(path.join(__dirname, 'website/initial', 'index.html'));
    }
});

var server = app.listen(3000);

var firstTime = true;

var connections = [];

var io = socket(server);
io.on('connection', function(socket) {
    console.log('Connection established. Sending user data...');
    spotifyApi.getMe().then(
        function(data) {
            socket.emit('user', data);
        }, function(err) {
            console.log('Something went wrong in getMe()!', err);
        });

    connections.forEach(function(object) {
        if(object.ip == socket.handshake.address) {
            console.log('Ip connected previously under \'' + object.name + '\'. Sending established name... ');
            socket.emit('returning_user', object.name);
        }
    });

    io.sockets.emit('connections', connections);

    //search bar
    socket.on('search', function(search_data) {
        spotifyApi.searchTracks(search_data.body, { limit: 30 }).then(
        function(data) {
            console.log('Search request for ' + search_data.body + ' from \'' + search_data.client_name + '\' ...');
            socket.emit('results', data);
        }, function(err) {
            console.log('Something went wrong in searchTracks()!', err);
        }
        )
    })

    socket.on('firstTime', function(name) {
        connections.push( { 'ip': socket.handshake.address, 'name': name });
        console.log(connections);
        io.sockets.emit('connections', connections);
    });

    //'Play' Button
    socket.on('request', function(request_data) {
        console.log('Request for ' + request_data.body.name + ' by ' + request_data.body.artist_name + ' from \'' + request_data.client_name + '\' ...');
        if(firstTime) {
            firstTime = false;
            spotifyApi.addTracksToPlaylist(playlistId, [request_data.body.uri])
                .then(function(data) {
                    playlist.push({ 'track': request_data, 'votes': 0});
                    
                    spotifyApi.play({context_uri: playlistUri}).then(
                        function(data) {
                        }, function(err) {
                            console.log('Something went wrong in play()!', err);
                        });

                }, function(err) {
                    console.log('Something went wrong in addTracksToPlaylist()!', err);
                });

        } else {
            spotifyApi.addTracksToPlaylist(playlistId, [request_data.body.uri])
                .then(function(data) {
                    playlist.push({ 'track': request_data, 'votes': 0, 'voters': []});

                    spotifyApi.getMyCurrentPlaybackState().then(
                        function(playback) {
                            if(playback.body.context == null) {
                                spotifyApi.play({context_uri: playlistUri, "offset": { "position": playlist.length - 1 }}).then(
                                    function(data) {
                                    }, function(err) {
                                        console.log('Something went wrong in play()!', err);
                                });
                            }
                        }, function(err) {
                            console.log('Something went wrong in getMyCurrentPlaybackState()!', err);
                        });

                }, function(err) {
                    console.log('Something went wrong in addTracksToPlaylist()!', err);
                });
            
        }
        
    })

    socket.on('vote', function(vote_data) {
        console.log('Vote to Skip ' + playlist[vote_data.position].track.body.name + ' by ' + playlist[vote_data.position].track.body.artist_name + ' from \'' + vote_data.client_name + '\' ...');
        playlist[vote_data.position].votes++;
        playlist[vote_data.position].voters.push(vote_data.client_name);

        if(playlist[vote_data.position].votes == connections.length) {
            console.log('Sufficient votes received, removing/skipping ' + playlist[vote_data.position].track.body.name + ' by ' + playlist[vote_data.position].track.body.artist_name + ' ...');
            spotifyApi.getPlaylist(playlistId)
                .then(function(pl) {
                    spotifyApi.removeTracksFromPlaylistByPosition(playlistId, [vote_data.position], pl.body.snapshot_id)
                        .then(function(data) {
                            playlist.splice(vote_data.position);
                        }, function(err) {
                            console.log('Something went wrong in removeTracksFromPlaylistByPosition()!', err);
                        })
                }, function(err) {
                    console.log('Something went wrong in getPlaylist()!', err);
                })
            
        }
    })
})